// <auto-generated />
namespace LeanerProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class new_relationship_icons_classroms : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_relationship_icons_classroms));
        
        string IMigrationMetadata.Id
        {
            get { return "202404131222371_new_relationship_icons_classroms"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
