// <auto-generated />
namespace LeanerProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migration_new_db_messages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration_new_db_messages));
        
        string IMigrationMetadata.Id
        {
            get { return "202404281325482_migration_new_db_messages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
