// <auto-generated />
namespace LeanerProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migration_conatct_message_tables_Add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration_conatct_message_tables_Add));
        
        string IMigrationMetadata.Id
        {
            get { return "202404191858085_migration_conatct_message_tables_Add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
