// <auto-generated />
namespace LeanerProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migaration_remove_colm_for_table_about : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migaration_remove_colm_for_table_about));
        
        string IMigrationMetadata.Id
        {
            get { return "202404271109167_migaration_remove_colm_for_table_about"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
